#include<stdio.h>
int main () {
	int A[5][5], B[5], C[5], a, b, d; //Declarando meus vetores e variáveis
	for (a = 0; a < 5; a++) { //Laço para leitura do Vetor 2D
		for (b = 0; b < 5; b++) { //Mais um laço...
			printf ("Digite um numero:\n"); //Mensagem para o usuário
			scanf ("%i", &A[a][b]);}} //Passando valores Para o vetor
	for (a = 0; a < 5; a++) { //Laço para passar valor para meus vetores
		C[a] = 0; //Atribuindo valor
		B[a] = 0;} //Mais atribuição
	for (a = 0; a < 5; a++) { //Laço para soma das linhas
		for (b = 0; b < 5; b++) { //Mais laço...
			C[a] += A[a][b];}} //Conta...
	for (a = 0; a < 5; a++) { //Laço para a soma das colunas...
		for (b = 0; b < 5; b++) { //Mais laço...
			B[a] += A[b][a];}} //Mais conta...
	for (a = 0; a < 5; a++) { //Laço para mostrar a soma das minhas linhas...
		printf ("A soma da linha %i e: %i\n", a, C[a]);} //Mensagem para o usuário
	for (a = 0; a < 5; a++) { //Outro laço para mostrar a soma das colunas
		printf ("A soma da coluna %i e: %i\n", a, B[a]);} //Mensagem para o usuário...
	return 0;} //Fim do programa :D
