#include<stdio.h>
int main () {
	int a = 1, b = 0, c = 0; //Indicando as variáveis e atribuindo os respectivos valores
	while (a <= 500) { //Enquanto a for menor ou igual a 500...
		if (a % 2 == 0) { c = b + a; //se a for par, segue...
			b = c; //atribuindo valores
			a++;} //Acrementando valor no a
		else //Senão...
		if (a % 2 != 0) { //Se a for ímpar
		a++;}} //Acremendo no valor de a
	printf ("%i", c); //Mostrando o resultaod final
	return 0;} //Fim...
