#include<stdio.h>
int main (){
	int a = 1; //Indicando as variáveis e passando o valor para as variáveis.
	while (a <= 20) { //Enquanto a menor ou igual a 20, segue
		if (a % 2 == 0) { //Se a for par, segue.
			printf ("%i e par\n", a); //Mostre essa mensagem
			a++;} //Acremento no a.
		else //Senão...
		if (a % 2 != 0) { //Se a for impar, segue...
			printf ("%i e impar \n", a); //Caso ele seja impar mostre essa mensagem...
			a++;}} //Acremento no a...
	return 0;} //Fim do programa
