#include<stdio.h>
int main () {
	int a; //Indicando minhas variáveis...
	for (a = 1; a < 21; a++){ //Para a igual a 1, menor que 21 acrementa no a sempre que o termo de baixo repetir...
		printf ("%i\n", a);} //Mostre a variável a sempre que a menor que 21...
	return 0;} //Fim do programa
