#include<stdio.h>
int main () {
	int a; //Indicando minha variável inteira...
	for (a = 2; a < 20; a++) { //Para a entre 1 e 20, acrementa no a sempre que o termo de baixo for repetido...
		if (a % 2 != 0){ //Se a for ímpar, segue
			printf ("%i\n", a);}} //Mostre a...
	return 0;} //Fim do programa...
