#include<stdio.h>
int main () {
	int a = 1; //Indicando e passando valores para minhas variáveis inteiras...
	do {printf ("%i\n", a); //Sempre force a mostrar
		a++;} while (a < 21); //Acremento no a, enquando a menor que 21...
	return 0;} //Fim...
