#include<stdio.h>
int main (){
	int a = 1; //Indicando as variáveis e passando o valor para as variáveis.
	do {if (a % 2 == 0) { //Force a ver se é par....
			printf ("%i e par\n", a); //Mostre essa mensagem sempre que par
			a++;} //Acremento no a.
		else //Senão...
		if (a % 2 != 0) { //Se a for impar, segue...
			printf ("%i e impar \n", a); //Caso ele seja impar mostre essa mensagem...
			a++;}} while (a <= 20); //Enquanto estiver entre 0 e 21, rode o programa, enquanto sempre acrementa o a...
	return 0;} //Fim do programa...
