#include<stdio.h>
int main()
{
	int a, b, c; //Indicando minha variáveis inteiras.
	printf ("Meu amiguinho me fale o valor das suas variaveis a e b, respectivamente:\n"); //Conversando com o usuário.
	scanf ("%i %i", &a, &b); //Passando valores para minhas variáveis...
	c = a; //Trocando valores...
	a = b; //Mais trocas...
	b = c; //Ainda mais trocas...
	printf ("Aqui tuas variaveis... a:\n %i\nE b:\n %i", a, b); //Mostrando meus valores...
	return 0; //Terminei...
}
